# Generated by Django 3.0.4 on 2020-06-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resource',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.Resource'),
        ),
        migrations.AlterField(
            model_name='event',
            name='winners',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.Winner'),
        ),
    ]
