# Generated by Django 3.0.4 on 2020-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20200622_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tag',
        ),
        migrations.AddField(
            model_name='resource',
            name='tag',
            field=models.ManyToManyField(to='MyApp.Tag'),
        ),
    ]
