# Generated by Django 3.0.4 on 2020-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20200622_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='year_1',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=12),
        ),
        migrations.AlterField(
            model_name='winner',
            name='year_2',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=12),
        ),
        migrations.AlterField(
            model_name='winner',
            name='year_3',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=12),
        ),
    ]
