# Generated by Django 3.0.4 on 2020-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_remove_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='profile/')),
                ('skills', models.CharField(max_length=40)),
                ('codechef_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('twitter_link', models.URLField(blank=True, default='http://127.0.0.1:8000/events', max_length=100)),
                ('github_link', models.URLField(blank=True, default='http://127.0.0.1:8000/events', max_length=100)),
                ('linked_in_link', models.URLField(blank=True, default='http://127.0.0.1:8000/events', max_length=100)),
                ('email_id', models.URLField(blank=True, default='http://127.0.0.1:8000/events', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
