# Generated by Django 3.0.4 on 2020-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20200623_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='email_id',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='github_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='static/images/withoutProfile.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='linked_in_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url_link',
            field=models.URLField(),
        ),
    ]
