# Generated by Django 3.0.4 on 2020-06-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_auto_20200623_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'AboutUs'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='linked_in_link',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='twitter_link',
        ),
    ]
