# Generated by Django 3.0.4 on 2020-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20200624_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='profile/withoutProfile.png', upload_to='profile/'),
        ),
    ]
