# Generated by Django 3.0.4 on 2020-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20200624_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='Symbol',
            field=models.CharField(blank=True, choices=[('bootstrap', 'bootstrap'), ('Node_JS', 'Node_JS'), ('Python', 'Python'), ('React_JS', 'React_JS'), ('Ruby', 'Ruby')], max_length=20),
        ),
    ]
