# Generated by Django 3.0.4 on 2020-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_resource_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Symbol',
            field=models.CharField(blank=True, choices=[('bootstrap', 'bootstrap'), ('Node_JS', 'Node_JS'), ('Python', 'Python'), ('React_JS', 'React_JS'), ('Ruby', 'Ruby')], default='default', max_length=20),
        ),
    ]
