# Generated by Django 3.0.4 on 2020-06-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20200624_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='Symbol',
        ),
        migrations.AddField(
            model_name='resource',
            name='symbol',
            field=models.CharField(blank=True, choices=[('AngularJS', 'AngularJS'), ('bootstrap', 'bootstrap'), ('C#', 'C#'), ('C', 'C'), ('C++', 'C++'), ('DataBase', 'DataBase'), ('Django', 'Django'), ('Java', 'Java'), ('Node_JS', 'Node_JS'), ('Python', 'Python'), ('React_JS', 'React_JS'), ('Ruby', 'Ruby')], default='default', max_length=20),
        ),
    ]
