# Generated by Django 3.0.4 on 2020-06-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_resource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.Resource'),
        ),
    ]
