# Generated by Django 3.0.4 on 2020-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_auto_20200624_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(upload_to='Resource_Gallery/'),
        ),
    ]
