# Generated by Django 3.0.4 on 2020-06-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_auto_20200624_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
    ]
