# Generated by Django 3.0.4 on 2020-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_remove_resource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organised_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
