# Generated by Django 3.0.4 on 2020-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_event_organised_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_emailId', models.CharField(max_length=50)),
                ('Enrollment_No', models.IntegerField(max_length=7)),
                ('BlogTitle', models.CharField(max_length=40)),
                ('BlogDesc', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='Blog_Post/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
