# Generated by Django 3.0.4 on 2020-06-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_auto_20200625_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Blog',
            new_name='UserBlog',
        ),
    ]
